// <auto-generated />
using System;
using JNCollection.Website.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JNCollection.Website.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210824095204_ShoppingCartAdded")]
    partial class ShoppingCartAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JNCollection.Website.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Man wear"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Women wear"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Children wear"
                        });
                });

            modelBuilder.Entity("JNCollection.Website.Models.Clothe", b =>
                {
                    b.Property<int>("ClotheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbanailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClotheOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClotheId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Clothes");

                    b.HasData(
                        new
                        {
                            ClotheId = 1,
                            CategoryId = 1,
                            ImageThumbanailUrl = "https://cdn-images.farfetch-contents.com/14/37/02/55/14370255_23742822_1000.jpg",
                            ImageUrl = "https://cdn-images.farfetch-contents.com/14/37/02/55/14370255_23742822_1000.jpg",
                            InStock = true,
                            IsClotheOfTheWeek = true,
                            LongDescription = "Wear it with Love",
                            Name = "White-Tshirt",
                            Price = 12.95m,
                            ShortDescription = "Our Lovely T-shirt"
                        },
                        new
                        {
                            ClotheId = 2,
                            CategoryId = 2,
                            ImageThumbanailUrl = "https://cdn-images.farfetch-contents.com/14/37/02/55/14370255_23742822_1000.jpg",
                            ImageUrl = "https://cdn-images.farfetch-contents.com/14/37/02/55/14370255_23742822_1000.jpg",
                            InStock = true,
                            IsClotheOfTheWeek = true,
                            LongDescription = "Wear it with Love",
                            Name = "White-Tshirt",
                            Price = 12.95m,
                            ShortDescription = "Our Lovely T-shirt"
                        },
                        new
                        {
                            ClotheId = 3,
                            CategoryId = 3,
                            ImageThumbanailUrl = "https://cdn-images.farfetch-contents.com/14/37/02/55/14370255_23742822_1000.jpg",
                            ImageUrl = "https://cdn-images.farfetch-contents.com/14/37/02/55/14370255_23742822_1000.jpg",
                            InStock = true,
                            IsClotheOfTheWeek = true,
                            LongDescription = "Wear it with Love",
                            Name = "White-Tshirt",
                            Price = 12.95m,
                            ShortDescription = "Our Lovely T-shirt"
                        },
                        new
                        {
                            ClotheId = 4,
                            CategoryId = 1,
                            ImageThumbanailUrl = "https://cdn-images.farfetch-contents.com/14/37/02/55/14370255_23742822_1000.jpg",
                            ImageUrl = "https://cdn-images.farfetch-contents.com/14/37/02/55/14370255_23742822_1000.jpg",
                            InStock = true,
                            IsClotheOfTheWeek = true,
                            LongDescription = "Wear it with Love",
                            Name = "White-Tshirt",
                            Price = 12.95m,
                            ShortDescription = "Our Lovely T-shirt"
                        },
                        new
                        {
                            ClotheId = 5,
                            CategoryId = 2,
                            ImageThumbanailUrl = "https://cdn-images.farfetch-contents.com/14/37/02/55/14370255_23742822_1000.jpg",
                            ImageUrl = "https://cdn-images.farfetch-contents.com/14/37/02/55/14370255_23742822_1000.jpg",
                            InStock = true,
                            IsClotheOfTheWeek = true,
                            LongDescription = "Wear it with Love",
                            Name = "White-Tshirt",
                            Price = 12.95m,
                            ShortDescription = "Our Lovely T-shirt"
                        },
                        new
                        {
                            ClotheId = 6,
                            CategoryId = 3,
                            ImageThumbanailUrl = "https://cdn-images.farfetch-contents.com/14/37/02/55/14370255_23742822_1000.jpg",
                            ImageUrl = "https://cdn-images.farfetch-contents.com/14/37/02/55/14370255_23742822_1000.jpg",
                            InStock = true,
                            IsClotheOfTheWeek = true,
                            LongDescription = "Wear it with Love",
                            Name = "White-Tshirt",
                            Price = 12.95m,
                            ShortDescription = "Our Lovely T-shirt"
                        });
                });

            modelBuilder.Entity("JNCollection.Website.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("ClotheId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("ClotheId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("JNCollection.Website.Models.Clothe", b =>
                {
                    b.HasOne("JNCollection.Website.Models.Category", "Category")
                        .WithMany("Clothes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JNCollection.Website.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("JNCollection.Website.Models.Clothe", "Clothe")
                        .WithMany()
                        .HasForeignKey("ClotheId");

                    b.Navigation("Clothe");
                });

            modelBuilder.Entity("JNCollection.Website.Models.Category", b =>
                {
                    b.Navigation("Clothes");
                });
#pragma warning restore 612, 618
        }
    }
}
